debug: false # Enable debug logs.
trace: false

#para conecar con postgresql  
spring:
  mvc:
    contentnegotiation: # estos son para configurar la exportacion a pdf
      favor-parameter: true
      media-types:
        pdf: application/pdf
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet        
  banner:
    location: classpath:banner-omr.txt # Banner file location.
  datasource:
    url: jdbc:postgresql://localhost:5432/sisescolar
    username: u_sisescolar
    password: comr040488
  jpa:    
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update                          
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect                     